### ISSUE TITLE
Did you train your models on ImageNet-1K from scratch?

### ISSUE THREAD

**Issue by khawar-islam** [mmmmimic/OOD-CV-challenge#1]
Dear @mmmmimic 

Thank you for the work. Did you train Convnext and Swin ViTs from scratch on imageNet-1k?
Did you use below dataset? 
https://www.kaggle.com/competitions/imagenet-object-localization-challenge/data

Regards,
Khawar

**Comment by mmmmimic** [comment]
Dear Khawar, 

Thank you for your interest in our work! We did not train ConvNext or Swin from scratch - we simply loaded the pre-trained parameters provided by [pytorch-image-models](https://github.com/rwightman/pytorch-image-models). [Here](https://rwightman.github.io/pytorch-image-models/) is an example from the official documentation. 

BR,
Manxi

**Comment by mmmmimic** [comment]
![image](https://user-images.githubusercontent.com/46046604/203514811-848b7f80-e7b9-42eb-8732-2e396b127672.png)

**Comment by khawar-islam** [comment]
Dear Manxi,

Thank you for your clarification.
